# Generated by Django 3.2.14 on 2022-07-24 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizito', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegistrationModel',
        ),
    ]
