# Generated by Django 3.2.14 on 2022-07-25 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizito', '0003_category_marks_question_ranks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='ranks',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='category',
            name='no_of_questions',
        ),
        migrations.AddField(
            model_name='category',
            name='categoryid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='quesid',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
        migrations.DeleteModel(
            name='Ranks',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizito.category'),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
